INSERT INTO music
(song, artist, genre, id, likes)
VALUES
('The 1st chapter', 'Uniolla', , '32rhuRkjXzumTIGN5ENqsK', 0),
('246', 'Straightener', , '1dfVdOypzMENs6qfO6PAz2', 0),
('Aliens', 'The Burning Deadwoods', , '1C7KgZWz1FgW3D2txHtbYd', 0),
('ALL THE TIME', 'ROU', , '1rxdr9TEb4lINwvWUE0J7y', 0),
('AMERICA HAS A PROBLEM (feat. Kendrick Lamar)', 'Beyoncé', , '6l8mgVN9Xf1hiDIFGA6CTE', 0),
('ARE YOU DOWN?', 'MÖSHI', , '7Ky4jdIF31Jy8rL3VRRsKB', 0),
('Bad Bitch 美学', 'Various Artists', , '6fjabsh5BstmT5jFwK7JMq', 0),
('Bite Me', 'ENHYPEN', , '7mpdNiaQvygj2rHoxkzMfa', 0),
('Call My Name', 'Bullet Train', , '6GkT8PTDQgeHGOWHyOYrSb', 0),
('Call out', 'Blu-Swing', , '3eaoxObc2n7viuxcL6fogs', 0),
('CHEESE', 'Issei Uno Fifth', , '6b8of1wtergsZvlTgGCSNy', 0),
('Cruisin’ Till Sunrise : 日の出まで クルージング feat. Neighbors Complain', 'ETC.', , '1nKpEucJZZGV0UT96k21aa', 0),
('Devotion', 'Arlo Parks', , '6w6gCLDgv4L5AJtVDJNddn', 0),
('Ding Ding Dong', 'BALLISTIK BOYZ from EXILE TRIBE', , '34SdlF91Zn6as6hGC7H8Md', 0),
('D.N.A.', 'Various Artists', , '2FqYiYp69tXh65B1juanLf', 0),
('Dominoes', 'Jungle', , '6OxxyMkPXG9jn5V9n11Sz1', 0),
('Don"t Forget About Me', 'd4vd', , '43rGLaawHXspfnWtBCoAQg', 0),
('DROP', 'INI', , '1CdAwTRMzcNRYGFh3tpRIK', 0),
('GIFT', 'Ry', , '7EcsL1UgEllJAVGlyy8jJK', 0),
('GREENAPPLE', '4na', , '5nXP1BgrG7yFiYfAkU5cCB', 0),
('Hallelujah', 'UEBO', , '67hYW1lINtVv2m1TTUyasq', 0),
('Heat Wave', 'Superfly', , '0D9OxfLHoA4Fk1LpHeCCJH', 0),
('a (hey)', 'Thiiird Place', , '1sGH32pmXnEhI5myHYhYi1', 0),
('How"s The Weather?', 'aimi', , '2fDYeWXk5CZa5fDu55TXVR', 0),
('into the wind', 'YONA YONA WEEKENDERS', , '19w7X63R92axa6x8azXjmb', 0),
('i want you so bad', 'shosha', , '7ITSWi6cBKQYJhHFpKqrj4', 0),
('L.M.S.N feat. Kyunchi', 'MANON', , '6fFrBnPlSalqXYL7rO6DY5', 0),
('Long Sleeper', 'Jua', , '12VpaLEVRSeS7NP6KYDeTQ', 0),
('MAKE IT BOUNCE', 'Tokyo Young Vision', , '0vaE8jaKlZW0Gpr6l6wXfV', 0),
('Malfunction', 'Buffalo Daughter', , '377hVCm0NXiGhjXtnN2CHG', 0),
('mango run', 'Mall Boyz', , '2ExGR8upNu2ZXt6vdq0NjB', 0),
('Memories', 'YonYon', , '70xUGkgJZR9wMSTT7GmDGz', 0),
('Mourning', 'Post Malone', , '0gWrMbx6pbdH3n3nsLjE55', 0),
('The Narcissist', 'Blur', , '35d93v9AXADp8Wc0qJ3mIo', 0),
('New Day Rising', 'Subway Daydream', , '6tzmPuLpRY05wcR9pM9URK', 0),
('Night and Day', 'GuruConnect', , '51sJT3roX9nA10WTVJ7Kmz', 0),
('No One Is feat. aimi (Blended by tofubeats)', 'BACARDI RECORDS', , '3kiRZqFyrOzLWMLAoM7G6a', 0),
('Ordinary', 'Saori Hayami', , '1La7Y5rBnGGqnOlYft3BFf', 0),
('REPRESENT', 'Kowree', , '6MXo7loKZAR59EoymgcTeV', 0),
('Scene', 'Da-iCE', , '3I8vxjgarLR7TCgAUmKiYe', 0),
('Soft', 'Singer"s High', , '6fJ7pVUaGvOzsuZ3jDHNY2', 0),
('Space Orphans', 'Ichiko Aoba', , '3E3zIUB3qklDyq0RAFTfYD', 0),
('Stars', 'PNAU', , '2fNaMBJBFpv1PQ1zXkxIcO', 0),
('Stella"s Cough', 'Senri Oe', , '7c6RAOcYgwDFf0R6gusrbr', 0),
('STRAIGHT UP', 'CYBER RUI', , '2Wgc8Sag9Vm17eudpNZg0S', 0),
('Super Bloom', 'SHE"S', , '3Y5gwOygUw5rv0QFT8uWnY', 0),
('Tableaux タブローズ', 'cero', , '3JN19bBEL7y9kQpsUPWnM2', 0),
('Take It Back', 'YOUYA', , '2ephDESxMQBSKEKZRPNA1c', 0),
('T.H.E. feat.JUDY.', 'SMOKIN’theJAZZ', , '0Y5wlmlSkc375C3vpCkFzh', 0),
('Time To Go', 'Hannah Warm', , '3NXhxhKuqrCIs0JiSZha4U', 0),
('Tonight', 'the engy', , '3J2HYM8rgVDqXhlzsOztwG', 0),
('TRANSIT IN SUMMER', 'GOOD BYE APRIL', , '71rNG9Gx5bo66KCDjpkBUQ', 0),
('What’s Poppin', 'JP THE WAVY', , '6BkEiNQdMlwxPMgFDLkZtV', 0),
('WISE', 'voquote', , '17rNKPoxgh6liNaHIJdmpO', 0),
('Yaseino Kaze', 'Priscilla Ahn', , '3L0iroPfpyrbPSudJkXopI', 0),
('カメとピューマとフラミンゴ', 'KICK THE CAN CREW', , '2HUi7zcr41Gkl8ggCua8Et', 0),
('かもめのめ', 'Ukata', , '0wq6B3vqByYEMNCKidSJ2R', 0),
('コハルビヨリ', 'ERWIT', , '4hAZaUKLgGZ8qgHl88U8Fq', 0),
('ハルケシ', 'グソクムズ', , '35r5R6H2wyjkOsbvGh0YiX', 0),
('ふにょい', '和ぬか', , '5rarZdrHGVgQYjsqOMlSMp', 0),
('みんなウルサイ -STFU', 'YAYOI DAIMON', , '13tLE7EfMTIhaG6RZcntuE', 0),
('やらかした', 'MARIA', , '6KDhbwRCxX41VehN3aTIUu', 0),
('ライナー', 'Regal Lily', , '4cg4axRQFCLY7cxEQ8r0xe', 0),
('ラブシック', '須田景凪', , '2WL59zsWjW7VhGS6WVakZr', 0),
('リスペクト', 'AI', , '2KeMTeulC5A6oArHuzDx1i', 0),
('リバイバル', 'wacci', , '1Yn90hGurgZXXeAkiyHjqv', 0),
('七夕の夜、君に逢いたい', 'Five Ⅱ Four', , '6I250T7L2iSmpdB41Q1BIo', 0),
('光の中へ', '結束バンド', , '5pRchw0E4RpVqIWcyVCrJv', 0),
('君は言うかな', 'tonun', , '41hpqH0V4sz4FvZ2JOfBDb', 0),
('帰ろう', 'never young beach', , '7DdBE5bGf8pOwTBye0xPi3', 0),
('愛らしく', 'Huwie Ishizaki', , '45uxfemGgxsn1l6HK9Xpmk', 0),
('未送信', 'miwa', , '1AMOwvITGn9V0duo3k7sWq', 0),
('洒落', 'オレンジスパイニクラブ', , '2seyDmK7gssRroUPX6KIUR', 0),
('百鬼夜行', 'R+...', , '4X6zrENMuFANqmKz6MIV7p', 0),
('私は猫の目', 'Sheena Ringo', , '1EIb4vsdJ3F0ZBb0x37QHd', 0),
('終わらないまま', 'フー・ドゥ・ユー・ラブ', , '4v9ParjlvfTNIEqG1jIMT9', 0),
('綺羅綺羅', 'Reol', , '1PYf8NPd7Q9xjtfjVCgPw1', 0),
('罠 (Rearrange)', 'THE BACK HORN', , '5UCym9qWS4ub6qFfmcaEbf', 0),
('風に抱かれて', 'CHIAKI SATO', , '6oi67BENpGTbBjxnaGlqDc', 0),
('透明少女 - Remastered 2014', 'Number Girl', , '6b5DOkHnZZOnJnhaWXjifT', 0),
('きっとね!', '中村佳穂', , '1aleydUWuiBfdhxe8CMyV1', 0);
