INSERT INTO music
(song, artist, genre, id)
VALUES
('The 1st chapter', 'Uniolla', , '32rhuRkjXzumTIGN5ENqsK'),
('246', 'Straightener', , '1dfVdOypzMENs6qfO6PAz2'),
('Aliens', 'The Burning Deadwoods', , '1C7KgZWz1FgW3D2txHtbYd'),
('ALL THE TIME', 'ROU', , '1rxdr9TEb4lINwvWUE0J7y'),
('AMERICA HAS A PROBLEM (feat. Kendrick Lamar)', 'Beyoncé', , '6l8mgVN9Xf1hiDIFGA6CTE'),
('ARE YOU DOWN?', 'MÖSHI', , '7Ky4jdIF31Jy8rL3VRRsKB'),
('Bad Bitch 美学', 'Various Artists', , '6fjabsh5BstmT5jFwK7JMq'),
('Bite Me', 'ENHYPEN', , '7mpdNiaQvygj2rHoxkzMfa'),
('Call My Name', 'Bullet Train', , '6GkT8PTDQgeHGOWHyOYrSb'),
('Call out', 'Blu-Swing', , '3eaoxObc2n7viuxcL6fogs'),
('CHEESE', 'Issei Uno Fifth', , '6b8of1wtergsZvlTgGCSNy'),
('Cruisin’ Till Sunrise : 日の出まで クルージング feat. Neighbors Complain', 'ETC.', , '1nKpEucJZZGV0UT96k21aa'),
('Devotion', 'Arlo Parks', , '6w6gCLDgv4L5AJtVDJNddn'),
('Ding Ding Dong', 'BALLISTIK BOYZ from EXILE TRIBE', , '34SdlF91Zn6as6hGC7H8Md'),
('D.N.A.', 'Various Artists', , '2FqYiYp69tXh65B1juanLf'),
('Dominoes', 'Jungle', , '6OxxyMkPXG9jn5V9n11Sz1'),
('DROP', 'INI', , '1CdAwTRMzcNRYGFh3tpRIK'),
('GIFT', 'Ry', , '7EcsL1UgEllJAVGlyy8jJK'),
('GREENAPPLE', '4na', , '5nXP1BgrG7yFiYfAkU5cCB'),
('Hallelujah', 'UEBO', , '67hYW1lINtVv2m1TTUyasq'),
('Heat Wave', 'Superfly', , '0D9OxfLHoA4Fk1LpHeCCJH'),
('a (hey)', 'Thiiird Place', , '1sGH32pmXnEhI5myHYhYi1'),
('into the wind', 'YONA YONA WEEKENDERS', , '19w7X63R92axa6x8azXjmb'),
('i want you so bad', 'shosha', , '7ITSWi6cBKQYJhHFpKqrj4'),
('L.M.S.N feat. Kyunchi', 'MANON', , '6fFrBnPlSalqXYL7rO6DY5'),
('Long Sleeper', 'Jua', , '12VpaLEVRSeS7NP6KYDeTQ'),
('MAKE IT BOUNCE', 'Tokyo Young Vision', , '0vaE8jaKlZW0Gpr6l6wXfV'),
('Malfunction', 'Buffalo Daughter', , '377hVCm0NXiGhjXtnN2CHG'),
('mango run', 'Mall Boyz', , '2ExGR8upNu2ZXt6vdq0NjB'),
('Memories', 'YonYon', , '70xUGkgJZR9wMSTT7GmDGz'),
('Mourning', 'Post Malone', , '0gWrMbx6pbdH3n3nsLjE55'),
('The Narcissist', 'Blur', , '35d93v9AXADp8Wc0qJ3mIo'),
('New Day Rising', 'Subway Daydream', , '6tzmPuLpRY05wcR9pM9URK'),
('Night and Day', 'GuruConnect', , '51sJT3roX9nA10WTVJ7Kmz'),
('No One Is feat. aimi (Blended by tofubeats)', 'BACARDI RECORDS', , '3kiRZqFyrOzLWMLAoM7G6a'),
('Ordinary', 'Saori Hayami', , '1La7Y5rBnGGqnOlYft3BFf'),
('REPRESENT', 'Kowree', , '6MXo7loKZAR59EoymgcTeV'),
('Scene', 'Da-iCE', , '3I8vxjgarLR7TCgAUmKiYe'),
('Space Orphans', 'Ichiko Aoba', , '3E3zIUB3qklDyq0RAFTfYD'),
('Stars', 'PNAU', , '2fNaMBJBFpv1PQ1zXkxIcO'),('STRAIGHT UP', 'CYBER RUI', , '2Wgc8Sag9Vm17eudpNZg0S'),
('Tableaux タブローズ', 'cero', , '3JN19bBEL7y9kQpsUPWnM2'),
('Take It Back', 'YOUYA', , '2ephDESxMQBSKEKZRPNA1c'),
('T.H.E. feat.JUDY.', 'SMOKIN’theJAZZ', , '0Y5wlmlSkc375C3vpCkFzh'),
('Time To Go', 'Hannah Warm', , '3NXhxhKuqrCIs0JiSZha4U'),
('Tonight', 'the engy', , '3J2HYM8rgVDqXhlzsOztwG'),
('TRANSIT IN SUMMER', 'GOOD BYE APRIL', , '71rNG9Gx5bo66KCDjpkBUQ'),
('What’s Poppin', 'JP THE WAVY', , '6BkEiNQdMlwxPMgFDLkZtV'),
('WISE', 'voquote', , '17rNKPoxgh6liNaHIJdmpO'),
('Yaseino Kaze', 'Priscilla Ahn', , '3L0iroPfpyrbPSudJkXopI'),
('カメとピューマとフラミンゴ', 'KICK THE CAN CREW', , '2HUi7zcr41Gkl8ggCua8Et'),
('かもめのめ', 'Ukata', , '0wq6B3vqByYEMNCKidSJ2R'),
('コハルビヨリ', 'ERWIT', , '4hAZaUKLgGZ8qgHl88U8Fq'),
('ハルケシ', 'グソクムズ', , '35r5R6H2wyjkOsbvGh0YiX'),
('ふにょい', '和ぬか', , '5rarZdrHGVgQYjsqOMlSMp'),
('みんなウルサイ -STFU', 'YAYOI DAIMON', , '13tLE7EfMTIhaG6RZcntuE'),
('やらかした', 'MARIA', , '6KDhbwRCxX41VehN3aTIUu'),
('ライナー', 'Regal Lily', , '4cg4axRQFCLY7cxEQ8r0xe'),
('ラブシック', '須田景凪', , '2WL59zsWjW7VhGS6WVakZr'),
('リスペクト', 'AI', , '2KeMTeulC5A6oArHuzDx1i'),
('リバイバル', 'wacci', , '1Yn90hGurgZXXeAkiyHjqv'),
('七夕の夜、君に逢いたい', 'Five Ⅱ Four', , '6I250T7L2iSmpdB41Q1BIo'),
('光の中へ', '結束バンド', , '5pRchw0E4RpVqIWcyVCrJv'),
('君は言うかな', 'tonun', , '41hpqH0V4sz4FvZ2JOfBDb'),
('帰ろう', 'never young beach', , '7DdBE5bGf8pOwTBye0xPi3'),
('愛らしく', 'Huwie Ishizaki', , '45uxfemGgxsn1l6HK9Xpmk'),
('未送信', 'miwa', , '1AMOwvITGn9V0duo3k7sWq'),
('洒落', 'オレンジスパイニクラブ', , '2seyDmK7gssRroUPX6KIUR'),
('百鬼夜行', 'R+...', , '4X6zrENMuFANqmKz6MIV7p'),
('私は猫の目', 'Sheena Ringo', , '1EIb4vsdJ3F0ZBb0x37QHd'),
('終わらないまま', 'フー・ドゥ・ユー・ラブ', , '4v9ParjlvfTNIEqG1jIMT9'),
('綺羅綺羅', 'Reol', , '1PYf8NPd7Q9xjtfjVCgPw1'),
('罠 (Rearrange)', 'THE BACK HORN', , '5UCym9qWS4ub6qFfmcaEbf'),
('風に抱かれて', 'CHIAKI SATO', , '6oi67BENpGTbBjxnaGlqDc'),
('透明少女 - Remastered 2014', 'Number Girl', , '6b5DOkHnZZOnJnhaWXjifT'),
('きっとね!', '中村佳穂', , '1aleydUWuiBfdhxe8CMyV1');
