INSERT INTO music (song, artist, genre, url, likes) VALUES
( 'The 1st chapter', 'Uniolla', , '32rhuRkjXzumTIGN5ENqsK', 0),
( '246', 'Straightener', , '1dfVdOypzMENs6qfO6PAz2', 0),
( 'Aliens', 'The Burning Deadwoods', , '1C7KgZWz1FgW3D2txHtbYd', 0),
( 'ALL THE TIME', 'ROU', , '1rxdr9TEb4lINwvWUE0J7y', 0),
( 'AMERICA HAS A PROBLEM (feat. Kendrick Lamar)', 'Beyoncé', , '6l8mgVN9Xf1hiDIFGA6CTE', 0),
( 'ARE YOU DOWN?', 'MÖSHI', , '7Ky4jdIF31Jy8rL3VRRsKB', 0),
( 'Bad Bitch 美学', 'Various Artists', , '6fjabsh5BstmT5jFwK7JMq', 0),
( 'Bite Me', 'ENHYPEN', , '7mpdNiaQvygj2rHoxkzMfa', 0),
( 'Call My Name', 'Bullet Train', , '6GkT8PTDQgeHGOWHyOYrSb', 0),
( 'Call out', 'Blu-Swing', , '3eaoxObc2n7viuxcL6fogs', 0),
( 'CHEESE', 'Issei Uno Fifth', , '6b8of1wtergsZvlTgGCSNy', 0),
( 'Cruisin’ Till Sunrise : 日の出まで クルージング feat. Neighbors Complain', 'ETC.', , '1nKpEucJZZGV0UT96k21aa', 0),
( 'Devotion', 'Arlo Parks', , '6w6gCLDgv4L5AJtVDJNddn', 0),
( 'Ding Ding Dong', 'BALLISTIK BOYZ from EXILE TRIBE', , '34SdlF91Zn6as6hGC7H8Md', 0),
( 'D.N.A.', 'Various Artists', , '2FqYiYp69tXh65B1juanLf', 0),
( 'Dominoes', 'Jungle', , '6OxxyMkPXG9jn5V9n11Sz1', 0),
( 'Don"t Forget About Me', 'd4vd', , '43rGLaawHXspfnWtBCoAQg', 0),
( 'DROP', 'INI', , '1CdAwTRMzcNRYGFh3tpRIK', 0),
( 'GIFT', 'Ry', , '7EcsL1UgEllJAVGlyy8jJK', 0),
( 'GREENAPPLE', '4na', , '5nXP1BgrG7yFiYfAkU5cCB', 0),
( 'Hallelujah', 'UEBO', , '67hYW1lINtVv2m1TTUyasq', 0),
( 'Heat Wave', 'Superfly', , '0D9OxfLHoA4Fk1LpHeCCJH', 0),
( 'a (hey)', 'Thiiird Place', , '1sGH32pmXnEhI5myHYhYi1', 0),
( 'How"s The Weather?', 'aimi', , '2fDYeWXk5CZa5fDu55TXVR', 0),
( 'into the wind', 'YONA YONA WEEKENDERS', , '19w7X63R92axa6x8azXjmb', 0),
( 'i want you so bad', 'shosha', , '7ITSWi6cBKQYJhHFpKqrj4', 0),
( 'L.M.S.N feat. Kyunchi', 'MANON', , '6fFrBnPlSalqXYL7rO6DY5', 0),
( 'Long Sleeper', 'Jua', , '12VpaLEVRSeS7NP6KYDeTQ', 0),
( 'MAKE IT BOUNCE', 'Tokyo Young Vision', , '0vaE8jaKlZW0Gpr6l6wXfV', 0),
( 'Malfunction', 'Buffalo Daughter', , '377hVCm0NXiGhjXtnN2CHG', 0),
( 'mango run', 'Mall Boyz', , '2ExGR8upNu2ZXt6vdq0NjB', 0),
( 'Memories', 'YonYon', , '70xUGkgJZR9wMSTT7GmDGz', 0),
( 'Mourning', 'Post Malone', , '0gWrMbx6pbdH3n3nsLjE55', 0),
( 'The Narcissist', 'Blur', , '35d93v9AXADp8Wc0qJ3mIo', 0),
( 'New Day Rising', 'Subway Daydream', , '6tzmPuLpRY05wcR9pM9URK', 0),
( 'Night and Day', 'GuruConnect', , '51sJT3roX9nA10WTVJ7Kmz', 0),
( 'No One Is feat. aimi (Blended by tofubeats)', 'BACARDI RECORDS', , '3kiRZqFyrOzLWMLAoM7G6a', 0),
( 'Ordinary', 'Saori Hayami', , '1La7Y5rBnGGqnOlYft3BFf', 0),
( 'REPRESENT', 'Kowree', , '6MXo7loKZAR59EoymgcTeV', 0),
( 'Scene', 'Da-iCE', , '3I8vxjgarLR7TCgAUmKiYe', 0),
( 'Soft', 'Singer"s High', , '6fJ7pVUaGvOzsuZ3jDHNY2', 0),
( 'Space Orphans', 'Ichiko Aoba', , '3E3zIUB3qklDyq0RAFTfYD', 0),
( 'Stars', 'PNAU', , '2fNaMBJBFpv1PQ1zXkxIcO', 0),
( 'Stella"s Cough', 'Senri Oe', , '7c6RAOcYgwDFf0R6gusrbr', 0),
( 'STRAIGHT UP', 'CYBER RUI', , '2Wgc8Sag9Vm17eudpNZg0S', 0),
( 'Super Bloom', 'SHE"S', , '3Y5gwOygUw5rv0QFT8uWnY', 0),
( 'Tableaux タブローズ', 'cero', , '3JN19bBEL7y9kQpsUPWnM2', 0),
( 'Take It Back', 'YOUYA', , '2ephDESxMQBSKEKZRPNA1c', 0),
( 'T.H.E. feat.JUDY.', 'SMOKIN’theJAZZ', , '0Y5wlmlSkc375C3vpCkFzh', 0),
( 'Time To Go', 'Hannah Warm', , '3NXhxhKuqrCIs0JiSZha4U', 0),
( 'Tonight', 'the engy', , '3J2HYM8rgVDqXhlzsOztwG', 0),
( 'TRANSIT IN SUMMER', 'GOOD BYE APRIL', , '71rNG9Gx5bo66KCDjpkBUQ', 0),
( 'What’s Poppin', 'JP THE WAVY', , '6BkEiNQdMlwxPMgFDLkZtV', 0),
( 'WISE', 'voquote', , '17rNKPoxgh6liNaHIJdmpO', 0),
( 'Yaseino Kaze', 'Priscilla Ahn', , '3L0iroPfpyrbPSudJkXopI', 0),
( 'カメとピューマとフラミンゴ', 'KICK THE CAN CREW', , '2HUi7zcr41Gkl8ggCua8Et', 0),
( 'かもめのめ', 'Ukata', , '0wq6B3vqByYEMNCKidSJ2R', 0),
( 'コハルビヨリ', 'ERWIT', , '4hAZaUKLgGZ8qgHl88U8Fq', 0),
( 'ハルケシ', 'グソクムズ', , '35r5R6H2wyjkOsbvGh0YiX', 0),
( 'ふにょい', '和ぬか', , '5rarZdrHGVgQYjsqOMlSMp', 0),
( 'みんなウルサイ -STFU', 'YAYOI DAIMON', , '13tLE7EfMTIhaG6RZcntuE', 0),
( 'やらかした', 'MARIA', , '6KDhbwRCxX41VehN3aTIUu', 0),
( 'ライナー', 'Regal Lily', , '4cg4axRQFCLY7cxEQ8r0xe', 0),
( 'ラブシック', '須田景凪', , '2WL59zsWjW7VhGS6WVakZr', 0),
( 'リスペクト', 'AI', , '2KeMTeulC5A6oArHuzDx1i', 0),
( 'リバイバル', 'wacci', , '1Yn90hGurgZXXeAkiyHjqv', 0),
( '七夕の夜、君に逢いたい', 'Five Ⅱ Four', , '6I250T7L2iSmpdB41Q1BIo', 0),
( '光の中へ', '結束バンド', , '5pRchw0E4RpVqIWcyVCrJv', 0),
( '君は言うかな', 'tonun', , '41hpqH0V4sz4FvZ2JOfBDb', 0),
( '帰ろう', 'never young beach', , '7DdBE5bGf8pOwTBye0xPi3', 0),
( '愛らしく', 'Huwie Ishizaki', , '45uxfemGgxsn1l6HK9Xpmk', 0),
( '未送信', 'miwa', , '1AMOwvITGn9V0duo3k7sWq', 0),
( '洒落', 'オレンジスパイニクラブ', , '2seyDmK7gssRroUPX6KIUR', 0),
( '百鬼夜行', 'R+...', , '4X6zrENMuFANqmKz6MIV7p', 0),
( '私は猫の目', 'Sheena Ringo', , '1EIb4vsdJ3F0ZBb0x37QHd', 0),
( '終わらないまま', 'フー・ドゥ・ユー・ラブ', , '4v9ParjlvfTNIEqG1jIMT9', 0),
( '綺羅綺羅', 'Reol', , '1PYf8NPd7Q9xjtfjVCgPw1', 0),
( '罠 (Rearrange)', 'THE BACK HORN', , '5UCym9qWS4ub6qFfmcaEbf', 0),
( '風に抱かれて', 'CHIAKI SATO', , '6oi67BENpGTbBjxnaGlqDc', 0),
( '透明少女 - Remastered 2014', 'Number Girl', , '6b5DOkHnZZOnJnhaWXjifT', 0),
( 'きっとね!', '中村佳穂', , '1aleydUWuiBfdhxe8CMyV1', 0),
( 'All About U', 'BALLISTIK BOYZ from EXILE TRIBE', , '14Ge9twhpPM3MVt54iHIfj', 0),
( 'A Beautiful Game', 'Ed Sheeran', , '3j2KSKjenkrIsnoANPxV7V', 0),
( 'The Best Kid (feat. Bonbero)', 'CHICO CARLITO', , '3goNXpx5TmTxoRvAOs4c0n', 0),
( 'Be Who You Are (Real Magic) (feat. JID, NewJeans & Camilo)', 'Jon Batiste', , '7fcZk7OXeFWD7DWybltVVf', 0),
( 'BOLD - feat. reina', 'VivaOla', , '0ysitHytpmV4P83IKMxxdF', 0),
( 'Booorn!!', 'Tempalay', , '48oPAi5Va2Qm3ep6q6506R', 0),
( 'The Bridge', 'd4vd', , '7MTHpsxtKVJaBL6e9WXzqD', 0),
( 'Canvas', 'Kaneee', , '1HasPp7AYTmRj9lHHfO3AT', 0),
( 'Catch a Wave', 'TWICE', , '2MbxU95EQZbdRo0biiC6M2', 0),
( 'Classic', 'IVE', , '6jSnUhuqsXWsmlTxvRDzl3', 0),
( 'Dance The Night (From Barbie The Album)', 'Dua Lipa', , '1vYXt7VSjH9JIM5oRRo7vA', 0),
( 'dawn break', 'periwinkles', , '26e7gjbVjxjWBnucSOJ66X', 0),
( 'Delicious', 'THE BOYZ', , '53gU09JrGtZfXTPBFpukKr', 0),
( 'Dream Out Loud - feat. ØZI', 'SKY-HI', , '5jEP1KTapV6wun91fLJchx', 0),
( 'Fallin', 'Shota Shimizu', , '13LEi43b0Jl5AFRqPACiCg', 0),
( 'Fallin’', 'Rude-α', , '4VngRmTuScuofkIwr7BAd1', 0),
( 'Hand in Hand', 'J SOUL BROTHERS III', , '7eGcXg9hSZ59WG9uVRv2Kt', 0),
( 'Happy Birthday, New You', 'androp', , '0Xq4zN6HIXbjNieLWTNee4', 0),
( 'Himitsu', 'maco marets', , '24IoqcqtWcdKL9HjmXfxso', 0),
( 'Hits Different', 'Taylor Swift', , '3xYJScVfxByb61dYHTwiby', 0),
( 'I am here', 'Ryu Matsuyama', , '3oY94FnUoK5sSVyExSFZDa', 0),
( 'I"d hate 2 B a girl like U', 'Kenta Dedachi', , '4yIYZWlm2JGAtRgZjrlQQ8', 0),
( 'It’s show time', 'Philosophy no Dance', , '6ggbyYlbMCzrnVKpb9jFMy', 0),
( 'Late Flower', 'Kamui', , '0SXGYWsI8NDtdPbCzljMIP', 0),
( 'Love Groovin"', 'DE DE MOUSE', , '5vXhl78aOAmAV1sLKJotwI', 0),
( 'maybe I love you', 'Ai Otsuka', , '3bptItQrsbwAi3O1stunkH', 0),
( 'Mo ai ni', 'She Her Her Hers', , '6iSG9jmLnHlXaYgbIlBCUP', 0),
( 'Monster 1', 'Ryuichi Sakamoto', , '7DRpF8gLkdWJ01S29MVaOa', 0),
( 'Nagisa', 'imase', , '0bdAQ9dwLA5cJtgM05PRKW', 0),
( 'New Romantic (feat. Maki Nomiya)', 'Night Tempo', , '4DAGg2adRd1PuKrnoUZXOP', 0),
( 'numb brain', 'SHIFT_CONTROL', , '4uJqW72XHX5eIiugU0z60D', 0),
( 'POPSONG', 'Shin Rizumu', , '2KrU3NXtbpPjFSzaOIP1tF', 0),
( 'PRAYER', 'Miliyah', , '7fY5LEY2zb9iAVXDvHNUD7', 0),
( 'RIGHT MIND', 'MPC GIRL USAGI', , '2p9XZr10ES5yeUD0EcBBpu', 0),
( 'The Teacher', 'Foo Fighters', , '4GPdQsRCRCidGgmCsK9I4a', 0),
( 'TOO MUCH TIME - feat. 児玉真吏奈', 'KENT VALLEY', , '4IbYbZV9LRTRXwS0LPVL2O', 0),
( 'Window', 'Gestalt Girl', , '4Z3RZPhUHiIm0l1Ik5FsTv', 0),
( 'YMT', 'TOKYO RAVE GROUPIE', , '46EUCBmFdyjmrkVX2dYqoX', 0),
( 'アタシ', 'syudou', , '6TP14XdyV4UfzawCmXFnzp', 0),
( 'アビが鳴く', 'PornoGraffitti', , '4ay9QE7G6hT0BLl51XXK3b', 0),
( 'エンドロールは悲しくない', 'DISH//', , '5t5P8hrL6svTFKfzgMsLZK', 0),
( 'おやすみ', 'This is LAST', , '76XAy9oJ58bE7VLfGdF375', 0),
( 'グッドモーニング', '友成空', , '3tFSDNkzBPKt0zBo4XUUyJ', 0),
( 'コパカバーナにて', '森永陽実', , '4Mw95cd8I1hx7NAq91FkTA', 0),
( 'サイダー', 'Bray me', , '1IQlJLwD6QA5N4yIbDeIxt', 0),
( 'ずっと', 'asmi', , '49JLGVj2xrkrJhpLZL24s2', 0),
( 'その1万で', 'AKKOGORILLA', , '4Ue91TzTNrcAuqtcvWAUBs', 0),
( 'たいしたもんだよ', '森 大翔', , '1ofWIY0SGBubobEqZR4M2u', 0),
( 'ダンディライオン', 'Toshihiko Tahara', , '4Lqaq5GNOgriXJCv8e73yh', 0),
( 'ないものねだり', 'Maaya Sakamoto', , '3ZSFHKTl8dLGLioGaWkYJj', 0),
( 'なんとかなる', 'gb', , '48YkskPhG2THuJny4cfQpv', 0),
( 'フシアワセ', 'れん', , '26TkBHFwts2pMl0xKoL2Mz', 0),
( 'ぼくたちダイナソー', 'SANABAGUN.', , '66gaaKhZK3TFHKtdy9zxqG', 0),
( 'やさしい嘘', '平理央', , '2nVL1N8IMMjzJSAcxvXBAd', 0),
( 'ラーメンライス', 'Limited Express (has Gone?)', , '0ycQpzijGEvtlgu9qMQyn8', 0),
( 'ランデブー', 'POP ART TOWN', , '2f8uKvA1wnSilrmcneWfkP', 0),
( '一生このまま', 'Mega Shinnosuke', , '1q4zRDIKKchOp9fijZf7Px', 0),
( '俄青', '光季', , '4ptrNeHcA09ErHaHvAHJ6a', 0),
( '僕らじゃなきゃだめになって', 'Haku.', , '6KIYsdABQFGyNOjYBLNvfJ', 0),
( '冬のミルク (Rearrange)', 'THE BACK HORN', , '7rKbvBzXFnvrDtDXXhe2XF', 0),
( '同じ月を見ていた', 'Mummy-D', , '4aYkKiK5Hdo0rQlbSy6uRp', 0),
( '向日葵', 'Age Factory', , '7gApMTH54kCLmdFsgr7rT8', 0),
( '夏日狂想', 'クレナズム', , '4YiiwI9UXNTT51BwojLcR8', 0),
( '大事なお知らせ。', 'ワンダフル放送局', , '1Ei3DGdcshetCXZGpIxoQ7', 0),
( '天使のキス', 'みらん', , '0BPqXMCGVxCIcBo7WPjOzj', 0),
( '季節すら追い抜いて', 'Teikokukissa', , '4P0Gq52E5FmBp4IAcJa2eh', 0),
( '愛がそれだけ - feat.原田郁子', 'the chef cooks me', , '5evxDN31KQyoJrqEB49QzV', 0),
( '愛されるために君は生まれた ※with KREVA, SEIJI KAMEDA', 'Sayuri Ishikawa', , '0RSYqEK4S6I7PDUM9cyRo6', 0),
( '早朝遊園地', 'SOMAOTA', , '4rUrsN4SNdFxVfzTYc2N8h', 0),
( '朝日のぬくもり', '江﨑文武', , '0945XJg88Eu5VUu7Lchpig', 0),
( '東京ミッドナイト', 'MY FIRST STORY', , '6yOsud5tOWwu4Hj43cW7Vc', 0),
( '楽園', 'Emerald', , '0XwEnnsW5Z46jIweSj2MzB', 0),
( '死んでくれ', 'Galileo Galilei', , '3zriGDrUvCWdY40Gd1xZGf', 0),
( '真夜中の天才たち', 'RAq', , '3yhE6LLxo4joBOwtf9Xmkn', 0),
( '罠 - Reprise', 'XinU', , '7IkJBiv4Gg3QoV5sYYl74A', 0),
( '蝉ダンスフロア', 'Maharajan', , '2o7cOj0V9YziUyLR8F1qpV', 0),
( '透明少女 - 4 / LIVE', 'Number Girl', , '4w7NG7srCNipghjLJxvUhK', 0),
( '青梅', 'Creep Hyp', , '0D0RLKxs1x9BfEnaFUfKCl', 0),
( 'アイドル', 'YOASOBI', , '7ovUcF5uHTBRzUpB6ZOmvt', 0),
( 'Season', 'iri', , '4rcAJoljlgzkYsisGJ1NsT', 0),
( '美しい鰭', 'SPITZ', , '1H3qOzheTPhE7aVvJOWfvA', 0),
( 'TATTOO', 'OFFICIAL HIGE DANDISM', , '36jIu8oPR1Z4cguMuHxUXA', 0),
( '絆ノ奇跡', 'MAN WITH A MISSION', , '2VBLFxCUyFp5BfmsZpxcis', 0),
( 'ケセラセラ', 'Mrs. GREEN APPLE', , '406ZlqOP9nLQxJFBY7d9S4', 0),
( 'Drink!', 'DURDN', , '16OYugyNRr5pxjWZEfkU6b', 0),
( 'Hare Hare', 'TWICE', , '0h3dJV8JA5oxPzSF4tkz2t', 0),
( 'LONGINESS REMIX', 'SugLawd Familiar', , '4WV6zSmQVMmgSAaY9M5bVE', 0),
( '斜陽', 'ヨルシカ', , '2U6mFmBDjaAu6oCCDRpRet', 0),
( '不法侵入', 'ZUTOMAYO', , '1BtLaNoJo4zXGaYRLjvACo', 0),
( 'Stray Hearts', 'Koshi Inaba', , '3sqx01xjg7G7Fehge1YqUP', 0),
( '心得', 'Uru', , '2hPBIYQeqpbQWSMAM9ln1w', 0),
( 'メフィスト', 'QUEEN BEE', , '45LUKiex0D78VuhP3Oz6mG', 0),
( 'フライデー・ナイト', 'natori', , '6MXlv5l2I2BRa9pO38dE1a', 0),
( 'LADY', 'Kenshi Yonezu', , '7w6NWogvAAFdEhD9MA2uvv', 0),
( 'そんなbitterな話', 'Vaundy', , '4QlSFkbRxZWkHDF1MqBaEY', 0),
( 'いばら', 'Ado', , '3xWRjOUp8oDOByEJbOVh6U', 0),
( 'boy - feat. asmi & imase', 'KERENMI', , '5ZpYanxEoJRJjfWJORq2Jf', 0),
( 'メリーゴーランド', 'Yuuri', , '2MsDVWHcrBexkP9zOIWz4R', 0),
( 'ピンクブルー', 'Ryokuoushoku Shakai', , '1VRwCezjpvjnCrab92b1dk', 0),
( '夢はさめても', 'TOMOO', , '6qGRdMmPJzb5hA6eqTegnG', 0),
( 'W●RK', 'millennium parade', , '1L50ymp25Vmu7VnPRx5TWf', 0),
( 'Super Star', 'Furui Riho', , '4LCJXB7w5ZV0oT6cu9mv5k', 0),
( 'ターコイズ', 'SEKAI NO OWARI', , '4h0bg0R9tG0OplMXy9SVM2', 0),
( '愛してた(feat.れん)', 'Naoto Inti Raymi', , '2A9EvUkIWDDKWV6rcsM72a', 0),
( 'L7 Blues', 'LANA', , '3jlz3hv1rjQZSrrAtoRlXR', 0),
( '窓の中から', 'BUMP OF CHICKEN', , '0R96nqU10shRzLcbpPiNA7', 0),
( '名前は片想い', 'indigo la End', , '0o3zVVGJkb1QIOMF9xySiu', 0),
( '君のまま', '百足', , '78NUnAsLzE6azxvuPDy9M7', 0),
( '愛の花', 'Aimyon', , '4iBO3Jg6kSXZHw06db0ds3', 0),
( '色彩', 'Galileo Galilei', , '1xQkiYu0JiYpTCZ4tGMGit', 0),
( 'Suki Lie', 'ATARASHII GAKKO!', , '19Tzt6c75W1wUrXgv2WR2W', 0),
( '君の目も鼻も口も顎も眉も寝ても覚めても超素敵!!!', 'SHISHAMO', , '5Us9nHV0bOYJI7uh3wJQFf', 0),
( 'Symphony', 'HIRAIDAI', , '4TI7dRixtHok7njiL4CCaI', 0),
( 'GOLD', 'PEOPLE 1', , '1ZsZk1y1FF25JXT0ojTz2X', 0),
( 'LEFT RIGHT REMIXX - FEAT. CIARA & JACKSON WANG // PROD BY JAKOPS', 'XG', , '4Fd2BjzdKHzrc2uY7zmMar', 0),
( 'KANASHIBARI', 'RADWIMPS', , '4zJEGkmkmA4orRkMdzimRu', 0),
( '金剛力士像', 'WEDNESDAY CAMPANELLA', , '3y9ImuUtxOU6ZlAkbB5SRc', 0),
( 'merry-go-round', 'tonun', , '4RDjRmWez2gryxtIO2Attf', 0),
( 'I"m Not OK', 'CHANMINA', , '11nIII740gdZUWnNDKOwFh', 0),
( '愛してみてよ減るもんじゃないし', 'neguse.', , '4sCiH4LCVfHsMUmiK6GNGS', 0),
( '修羅の巷', 'KAMI WA SAIKORO WO FURANAI', , '5wnmQXqaj5JOOHN4xGUJRy', 0),
( '自由', 'tofubeats', , '7z0FfMMoJGsL6hgsoR0U6M', 0),
( 'まぶた', 'Vaundy', , '6YCwX5jlAEFL775YJqgLqN', 0);
